version: "3"

services:

  postgres:
    image: postgres
    tty: true
    container_name: lrucache_psql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lrucache_psql


  lrucache_app:
    image: lrucache_app:v0.1.0
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVE_PORT=8080
      - PSQL_DSN=host=postgres port=5432 user=postgres password=postgres dbname=lrucache_psql sslmode=disable
      - GIN_MODE=release
    ports:
      - "8080:8080"
